drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    bookmark_name text,
    bookmark_url text,
    bookmark_rating numeric,
    bookmark_content text
);

insert into bookmarks(bookmark_name, bookmark_url, bookmark_rating)
values
('Google', 'www.google.com', 5),
('Youtube', 'www.youtube.com', 5),
('Facebook', 'www.facebook.com', 5),
('Thinkful', 'www.thinkful.com', 5),
('github', 'www.github.com', 5),
('bloc', 'www.bloc.io', 5),
('thingiverse', 'www.thingiverse.com', 5),
('REI', 'www.REI.com', 5),
('Netflix', 'www.netflix.com', 5),
('stack overflow', 'www.stackoverflow.com', 5);